# Generated by Django 4.2.7 on 2023-11-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_tag_book_vote_ratio_book_vote_total_reviews_book_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bode',
            new_name='body',
        ),
    ]
